//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class four_in_row_DB_AbolielEntities : DbContext
    {
        public four_in_row_DB_AbolielEntities()
            : base("name=four_in_row_DB_AbolielEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CurrentGame_Entity> CurrentGame_Entity { get; set; }
        public virtual DbSet<Game_Entity> Game_Entity { get; set; }
        public virtual DbSet<HistoryGame_Entity> HistoryGame_Entity { get; set; }
        public virtual DbSet<Player_Entity> Player_Entity { get; set; }
    }
}
