//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game_Entity()
        {
            this.CurrentGame_Entity = new HashSet<CurrentGame_Entity>();
            this.HistoryGame_Entity = new HashSet<HistoryGame_Entity>();
        }
    
        public int Id { get; set; }
        public System.DateTime TimeStarting { get; set; }
        public string Winner { get; set; }
        public int CurrentGamesId { get; set; }
        public int HistoryGamesId { get; set; }
        public int FirstPlayer_Id { get; set; }
        public int SecondPlayer_Id { get; set; }
        public string PlayerTurn { get; set; }
        public int Player_EntityId { get; set; }
        public int Player_EntityId1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentGame_Entity> CurrentGame_Entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryGame_Entity> HistoryGame_Entity { get; set; }
        public virtual Player_Entity Player_Entity { get; set; }
        public virtual Player_Entity Player_Entity1 { get; set; }
    }
}
