//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryGame_Entity
    {
        public int Id { get; set; }
        public int IdGame { get; set; }
        public int Game_Entity_Id { get; set; }
    
        public virtual Game_Entity Game_Entity { get; set; }
    }
}
